---
- name: install all required packages
  hosts: local
  gather_facts: no
  tasks:
  - name: download and install all application stack
    apt: name={{ item }} state=present
    with_items:
      - curl
      - git
      - lsyncd
      - htop
      - redis-tools
