---
- name: install all required packages
  hosts: local
  gather_facts: no
  tasks:
  - name: download and install all application stack
    apt: name={{ item }} state=present
    with_items:
      - curl
      - git
      - lsyncd
      - htop
      - redis-tools
  - name: install docker-py
    pip: name=docker-py version=1.2.3
  - name: add docker repository into apt sources list
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-wily main' state=present # filename='docker'
  - name: add docker apt-key
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  - name: run apt-get update
    apt: update_cache=yes
  - name: install docker engine
    apt: name=docker-engine state=present
  - name: start docker service
    service: name=docker state=started
  - name: add user to docker group
    user: name=aliance groups=docker append=yes
  - name: new group
    command: newgrp docker
